name: '掘金 github actions'
on: 
 push:
 workflow_dispatch:
 schedule:
 # 定时任务 每天 8:00 自动签到，按照计划任务队列，可能延迟 0 + 8 = 北京时间 8
    - cron: '00 0 * * *'

jobs:
  juejin:
    runs-on: ubuntu-latest
    name: 掘金自动签到
    steps:
      - name: Hello world action step
        id: hello
        uses: lxchuan12/juejin-actions@main
        env: 
          JUEJIN_COOKIE: ${{secrets.JUEJIN_COOKIE}}
          MAIL_SENDER: ${{secrets.MAIL_SENDER}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
          MAIL_HOST_SENDER: ${{secrets.MAIL_HOST_SENDER}}
          MAIL_PORT_SENDER: ${{secrets.MAIL_PORT_SENDER}}
          MAIL_RECIPIENT: ${{secrets.MAIL_RECIPIENT}}
        with:
          who-to-greet: '若川'
      # Use the output from the `hello` step
      - name: Get the output
        run: | 
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "签到结果： ${{ steps.hello.outputs.checkInResult }}"